cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats, only: [:index, :show, :new, :create, :update, :edit]

end

cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord

  COLORS = ["white", "grey", "black", "gold", "yellow", "orange", "blue", "pink"]


  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :color, :inclusion => { :in => COLORS }
  validates :sex, :inclusion => { :in => ["M","F"] }

  def self.colors
    COLORS
  end

end

cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    #debugger
    render :new
    # debugger
  end

  def create
    # debugger
    if Cat.create!(cat_params)
      redirect_to cats_url
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cats_url
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date,:color,:name,:sex,:description)
  end
end

cats/app/helpers/application_helper.rb
module ApplicationHelper
end

cats/app/views/cats/edit.html.erb
<form action="/cats/<%= @cat.id %>" method="post">
  <input type="hidden" name="_method" value="patch" />

  <label for = "name"> Name </label>
  <input id = "name" type = "text" name = "cat[name]" value = "<%= @cat.name %>" >
  <br>

  <label for = "sex"> Sex </label>
  <input type="radio" name="cat[sex]" value="M" <%= @cat.sex=="M" ? "checked" : "" %>> Male
  <input type="radio" name="cat[sex]" value="F" <%= @cat.sex=="F" ? "checked" : "" %>> Female

  <br>

  <label for = "color"> Color </label>
  <select id = "color" name="cat[color]">
  <option> <%= @cat.color %> </option>
    <% Cat.colors.each do |color| %>
      <% next if color == @cat.color %>
      <option value= "<%= color %>"> <%= color %> </option>
    <% end %>
  </select>
  <br>

  <label for = "birth_date"> Birth date </label>
  <input type="date" name="cat[birth_date]" value="<%= @cat.birth_date %>">
  <br>

  <label for = "description"> Description </label>
  <textarea name="cat[description]"><%= @cat.description %></textarea>
  <br>

  <input type="submit" value="Update">
</form>

cats/app/views/cats/index.html.erb
  <% @cats.each do |cat| %>
    <ul>
    <li>name: <%= cat.name %></li>
    <li><%= link_to 'cat info',cat_url(cat) %></li>
    <li><%= button_to 'Update Cat!',cat_url(cat), method: 'patch' %></li>
    </ul>
  <% end %>

cats/app/views/cats/new.html.erb
<form action="/cats" method="post">
  
  <label for = "name"> Name </label>
  <input id = "name" type = "text" name = "cat[name]">
  <br>

  <label for = "sex"> Sex </label>
  <input type="radio" name="cat[sex]" value="M"> M
  <input type="radio" name="cat[sex]" value="F"> F
  <br>

  <label for = "color"> Color </label>
  <select id = "color" name="cat[color]">
  <option disable selected>--select a color--</option>
    <% Cat.colors.each do |color| %>
      <option value= "<%= color %>"> <%= color %> </option>
    <% end %>
  </select>
  <br>

  <label for = "birth_date"> Birth date </label>
  <input type="date" name="cat[birth_date]">
  <br>

  <label for = "description"> Description </label>
  <textarea name="cat[description]"></textarea>
  <br>

  <input type="submit" value="Create cat">
</form>

cats/app/views/cats/show.html.erb
  <table>
    <tr>
      <th>name</th>
      <th>birth_date</th>
      <th>sex</th>
      <th>color</th>
      <th>description</th>
    </tr>
    <tr>
      <td><%= @cat.name %></td>
      <td><%= @cat.birth_date %></td>
      <td><%= @cat.sex %></td>
      <td><%= @cat.color %></td>
      <td><%= @cat.description %></td>
    </tr>
  </table>
  <%= link_to 'all cats',cats_url %>

cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>